// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCma-R5X87a7Vw-HGXp2PSlWvpYE_Y7um8',
    appId: '1:909551492409:android:3fcd18b4d67436a7435ce8',
    messagingSenderId: '909551492409',
    projectId: 'dondonkkaseu-13dc1',
    storageBucket: 'dondonkkaseu-13dc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9i3D6_fTnj4j2Pa4weYDeBtmJtR4mXPc',
    appId: '1:909551492409:ios:ba3a07f3d7ba7f4c435ce8',
    messagingSenderId: '909551492409',
    projectId: 'dondonkkaseu-13dc1',
    storageBucket: 'dondonkkaseu-13dc1.appspot.com',
    iosBundleId: 'com.shinerdes.dondonkkaseu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9i3D6_fTnj4j2Pa4weYDeBtmJtR4mXPc',
    appId: '1:909551492409:ios:d274434dfe57fa8f435ce8',
    messagingSenderId: '909551492409',
    projectId: 'dondonkkaseu-13dc1',
    storageBucket: 'dondonkkaseu-13dc1.appspot.com',
    iosBundleId: 'com.example.dondonkkaseu.RunnerTests',
  );
}
